### ISSUE TITLE
Problems with training epochs on Dancetrack

### ISSUE THREAD

**Issue by yanghaibin-cool** [DanceTrack/DanceTrack#12]
@ifzhang Hi!
https://github.com/DanceTrack/DanceTrack/blob/18b60ea52ce03a7ed1710930663d810b461f460e/ByteTrack/exps/example/dancetrack/yolox_x.py#L25
Is it enough to train only 8 epochs on the DanceTrack dataset? Or is it a spelling mistake?Thanks for your reply!

**Comment by PeizeSun** [comment]
hi~
In our experiments, 8 epoch is enough. More training epochs don't help.

**Comment by Percyx0313** [comment]
hi~ @PeizeSun 
So we don't train the model again just use the weight in google drive you provide  ,right?
thank you.
