### ISSUE TITLE
hota.py如何调用

### ISSUE THREAD

**Issue by pandawynn** [DanceTrack/DanceTrack#13]
您好！请教下怎么实例化hota类啊，我看您给出了hota.py的代码，但是整个项目里好像没有调用hota的过程，所以不知道这个是怎么调用的，我想在自己的数据集上测一下hota这个指标。期待您的回复，谢谢！

**Comment by 459737087** [comment]
Hello! Did you solve it?

**Comment by pandawynn** [comment]
> Hello! Did you solve it?

Yes, you just need to follow the **Evaluation** in README.MD, 
i.e., python3 TrackEval/scripts/run_mot_challenge.py --SPLIT_TO_EVAL val  --METRICS HOTA CLEAR Identity  --GT_FOLDER dancetrack/val --SEQMAP_FILE dancetrack/val_seqmap.txt --SKIP_SPLIT_FOL True   --TRACKERS_TO_EVAL '' --TRACKER_SUB_FOLDER ''  --USE_PARALLEL True --NUM_PARALLEL_CORES 8 --PLOT_CURVES False --TRACKERS_FOLDER val/TRACKER_NAME

**Comment by 459737087** [comment]
> > Hello! Did you solve it?
> 
> Yes, you just need to follow the **Evaluation** in README.MD, i.e., python3 TrackEval/scripts/run_mot_challenge.py --SPLIT_TO_EVAL val --METRICS HOTA CLEAR Identity --GT_FOLDER dancetrack/val --SEQMAP_FILE dancetrack/val_seqmap.txt --SKIP_SPLIT_FOL True --TRACKERS_TO_EVAL '' --TRACKER_SUB_FOLDER '' --USE_PARALLEL True --NUM_PARALLEL_CORES 8 --PLOT_CURVES False --TRACKERS_FOLDER val/TRACKER_NAME

Thank u!! and I want to train on my own dataset , how to do it?

**Comment by liuqigui** [comment]
那你应该将你的数据集制作成这种形式的，然后将读取数据集的文件修改一下。之后，训练的方式和测试的方式和以前一样就可以了。
