### ISSUE TITLE
About the lstm motion model.

### ISSUE THREAD

**Issue by xiaocc612** [DanceTrack/DanceTrack#15]
Hi，
   Thanks for sharing your wondulf work. Is the [lstm model](https://github.com/DanceTrack/DanceTrack/blob/48d89d0d743b2a87de76525e6a948fc09f9f5f83/ByteTrack/yolox/tracker/lstm_predictor.py#L36) retrained by you? Or do you use the pre-trained model provided by DEFT? 
   Have a nice day ):

**Comment by PeizeSun** [comment]
hi~

I directly use the pre-trained model provided by DEFT.

**Comment by xiaocc612** [comment]
Thanks.
