### ISSUE TITLE
Hello! How many pip packges do I need to install?

### ISSUE THREAD

**Issue by 459737087** [DanceTrack/DanceTrack#16]
when I try to run ### **_python3 tools/train.py -f exps/example/dancetrack/yolox_x.py -d 8 -b 48 --fp16 -o -c pretrained/yolox_x.pth_**
But I fiailed, it told me there isn't train.py.

**Comment by PeizeSun** [comment]
Hi~
You should first git pull repo of ByteTrack, replace its files by our provided files, and then run the command under the folder of ByteTrack.
