### ISSUE TITLE
Evaluetion on DanceTrack test

### ISSUE THREAD

**Issue by iTruffle** [DanceTrack/DanceTrack#18]
Thank you for your great job.
I successfully run the code on DanceTrack test dataset, but I can not get the test result on https://codalab.lisn.upsaclay.fr/competitions/5832.
I get this error:
![image](https://user-images.githubusercontent.com/80766557/188770762-27dadf9d-b47a-44d2-8f3d-81506608b176.png)
How can I get the results of test set?

**Comment by PeizeSun** [comment]
hi~

This may be a problem of Codalab. Can you get the result now?

**Comment by iTruffle** [comment]
Yes. Thank you.

**Comment by liyi243** [comment]
错误怎么解决的呢
