### ISSUE TITLE
Is only the detector (e.g. YOLOX) to be trained in ByteTrack?

### ISSUE THREAD

**Issue by imzhangyd** [DanceTrack/DanceTrack#19]
Thanks for your wonderful work!
I think data association in ByteTrack is non-deep learning, which is not need to be trained.
Is only the detector (e.g. YOLOX) to be trained in ByteTrack?

**Comment by noahcao** [comment]
Yes, Bytetrack has no learning modules to be trained.

**Comment by xifen523** [comment]
Thank you very much for your efforts for MOT. I have some confusion about the YOLOX in this byteTrack, is it different from the original yolox, modified in the byteTrack?
Thank you very much.

**Comment by noahcao** [comment]
The used YOLOX detector is the same as ByteTrack repo.
