### ISSUE TITLE
Re-Evaluate QDTrack on Dancetrack

### ISSUE THREAD

**Issue by JennySeidenschwarz** [DanceTrack/DanceTrack#21]
Hello :)

I tried to re-evaluate QDtrack using the weights you provided but I cannot reproduce the results you reported in your paper. I get the following:

HOTA 45.8 / MOTA 83.0 / IDF1 44.8

Can you please tell me what I need to do to reproduce the results?

Best,
Jenny

**Comment by noahcao** [comment]
Hi,

In their latest paper here: https://arxiv.org/abs/2210.06984, they report the results on DanceTrack. I would recommend you to reach out to the authors of QDTrack for details.

**Comment by JennySeidenschwarz** [comment]
Thank you so much for your fast reply! I will ask them :)
