### ISSUE TITLE
请问实验结果Table 2中为什么输入检测框gt后DetA结果还是不一样呢

### ISSUE THREAD

**Issue by phyyyyy** [DanceTrack/DanceTrack#28]
DetA不是仅评估检测准确率嘛，为什么会跟随匹配策略改变，有点理解不上去了

**Comment by HELLORPG** [comment]
这个原因比较复杂，可以参考一下 HOTA 的原文，DetA 的计算并不仅仅依赖于 Detection 的结果（虽然这也让我很迷惑）。
或者是参考一下 [这个 issue](https://github.com/JonathonLuiten/TrackEval/issues/134)。


---------------------------------------------------------------
Refer to the paper of HOTA or [this issue](https://github.com/JonathonLuiten/TrackEval/issues/134).

**Comment by HELLORPG** [comment]
还有此外，尽管使用的都是 gt det，但是不同的 association 策略也会对检测结果进行不同程度的筛选，例如可能会丢弃一部分检测结果，从而带来 Det 的区别。


----
Moreover, although they use the same ground-truth detections, different association strategies may filter out different detections (maybe), resulting in different DetA metrics.

**Comment by noahcao** [comment]
Because DetA is designed to evaluation the quality of `associated detections` so the association quality also impacts the score.
