### ISSUE TITLE
如何得到hota指标

### ISSUE THREAD

**Issue by congyao123456** [DanceTrack/DanceTrack#33]
你好，请问如何在mot17上得到你readme上所说的hota指标，运行你给的代码只有IDF1   IDP   IDR  Rcll  Prcn  GT  MT  PT ML   FP    FN IDs   FM  MOTA  MOTP IDt IDa IDm num_objects

**Comment by noahcao** [comment]
For offline evaluation, you can use this toolkit: https://github.com/JonathonLuiten/TrackEval.

For formal evaluation, please submit to motchallenge evaluation server: https://motchallenge.net/
