### ISSUE TITLE
Google Drive link to trained models down

### ISSUE THREAD

**Issue by Eclair600** [DanceTrack/DanceTrack#36]
Hi, it seems like this link: https://drive.google.com/drive/folders/1IHDFBwyVMJew78H6a-gGtXMOb-fGZRlh?usp=sharing to download trained models is down. Do you think you could check it and reupdate it please.
Thanks in advance.

**Comment by noahcao** [comment]
We updated it. Now, we encourage to use huggingface instead of google drive link.
