### ISSUE TITLE
dancetrack和chocoholic联合训练问题

### ISSUE THREAD

**Issue by liu0623** [DanceTrack/DanceTrack#4]

**Comment by liu0623** [comment]
首先，对您的工作表示肯定，我在复现的时候发现了一些问题，请您解答。
1.处理dance和cocohp 后，新的文件包含哪些信息。
2.关键点训练的时候，对没有关键点的dance数据是如何处理的，在哪行代码有体现。

**Comment by noahcao** [comment]
This issue asks questions about joint training of dancetrack and coco_hp datasets:
1. After processing the dancetrack and cocohp datasets, what information is included in the the new annotation files.
2. How to process keypoint-unlabeled data from the dancetrack dataset.

Repose:
1. The output annotation of mixed dataset would be heterogenous, so for samples from dancetrack, they only contain bounding boxes annotation while those from coco would contain keypoint annotation. Please refer to the [data processing ](https://github.com/DanceTrack/DanceTrack/blob/main/CenterNet/joint_train/dancetrack_coco_hp.py)for details.
2. For keypoint-unlabeled dancetrack samples, during training, no keypoint-related loss would be put onto them. Namely, the keypoint loss only supervise the training of coco samples. You could refer to the[ training file ](https://github.com/DanceTrack/DanceTrack/blob/main/CenterNet/src/lib/trains/multi_pose.py)for details.

I'm closing this issue as I believe the response is clear. Feel free to reopen it if you have further follow-ups.
