### ISSUE TITLE
Dataset Statistic

### ISSUE THREAD

**Issue by QiyuLuo** [DanceTrack/DanceTrack#7]
Thank you for your excellent work. Is the **motion pattern** code not provided in the **dataset analysis**?  Can you share this part of the code?

**Comment by noahcao** [comment]
Hi, thanks for pointing that out. I have added the script to calculate that at: [oracle_analysis/motion_pattern_analysis.py](https://github.com/DanceTrack/DanceTrack/blob/main/oracle_analysis/motion_pattern_analysis.py)

However, by using the annotations on train and val subsets, your results won't be exactly the same with what we report in the paper. But the comparison results with other datasets should be aligned.
